spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tea_store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: test-user
    password: test-password
    druid:
      initial-size: 5
      max-active: 20