spring:
  datasource:
    url: jdbc:mysql://aliyun.com:3306/tea_store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: prod-user
    password: prod-password
    druid:
      initial-size: 5
      max-active: 20